version: '2'

services:
  insurance-ca:
    container_name: insurance-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: insurance-ca
    ports:
    - 7054:7054

  customer-ca:
    container_name: customer-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: customer-ca
    ports:
    - 8054:7054

  hospital-ca:
    container_name: hospital-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: hospital-ca
    ports:
    - 9054:7054

  orderer0:
    container_name: orderer0
    image: orderer
    environment:
    - ORDERER_GENERAL_LOGLEVEL=debug
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/orderer/crypto/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/orderer/crypto/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/crypto/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/crypto/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/orderer/crypto/tls/ca.crt]
    working_dir: /orderer
    command: orderer
    ports:
    - 7050:7050

  insurance-peer:
    container_name: insurance-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: insurance-peer
    environment:
    - CORE_PEER_ID=insurance-peer
    - CORE_PEER_ADDRESS=insurance-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=insurance-peer:7051
    - CORE_PEER_LOCALMSPID=InsuranceOrgMSP
    ports:
    - 7051:7051
    - 7053:7053
    depends_on:
    - orderer0

  customer-peer:
    container_name: customer-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: customer-peer
    environment:
    - CORE_PEER_ID=customer-peer
    - CORE_PEER_ADDRESS=customer-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=customer-peer:7051
    - CORE_PEER_LOCALMSPID=CustomerOrgMSP
    ports:
    - 8051:7051
    - 8053:7053
    depends_on:
    - orderer0
    - insurance-peer

  hospital-peer:
    container_name: hospital-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: hospital-peer
    environment:
    - CORE_PEER_ID=hospital-peer
    - CORE_PEER_ADDRESS=hospital-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=hospital-peer:7051
    - CORE_PEER_LOCALMSPID=HospitalOrgMSP
    ports:
    - 9051:7051
    - 9053:7053
    depends_on:
    - orderer0
    - insurance-peer
    - customer-peer