# This is Tek Systems HealthWise Network for Health Care Claims Problem Solve

version: '2'

volumes:
  orderer.healthwise.com:
  peer0.zigmainsurance.com:
  peer1.zigmainsurance.com:
  peer0.primecarehospital.com:
  peer1.primecarehospital.com:

networks:
  hwn:

services:

  orderer.healthwise.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.healthwise.com
    container_name: orderer.healthwise.com
    networks:
      - hwn

  peer0.zigmainsurance.com:
    container_name: peer0.zigmainsurance.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.zigmainsurance.com
    networks:
      - hwn

  peer1.zigmainsurance.com:
    container_name: peer1.zigmainsurance.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.zigmainsurance.com
    networks:
      - hwn

  peer0.primecarehospital.com:
    container_name: peer0.primecarehospital.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.primecarehospital.com
    networks:
      - hwn

  peer1.primecarehospital.com:
    container_name: peer1.primecarehospital.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.primecarehospital.com
    networks:
      - hwn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.zigmainsurance.com:7051
      - CORE_PEER_LOCALMSPID=zigmainsuranceMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/zigmainsurance.com/peers/peer0.zigmainsurance.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/zigmainsurance.com/peers/peer0.zigmainsurance.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/zigmainsurance.com/peers/peer0.zigmainsurance.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/zigmainsurance.com/users/Admin@zigmainsurance.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/healthclaims/go:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.healthwise.com
      - peer0.zigmainsurance.com
      - peer1.zigmainsurance.com
      - peer0.primecarehospital.com
      - peer1.primecarehospital.com
    networks:
      - hwn

